name: running shell command
on: push
jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: list the current directory
        run: pwd
  run-powershell-command:
    runs-on: windows-latest
    steps:
      - name: show the directory
        run: Get-Location      